customer/urls.py
from django.urls import path

from . import views

app_name = 'customer'

urlpatterns = [
    path('', views.customer, name='customer'),
    path('kumpulan-semangat/', views.post_semangat, name='semangat'),
    path('berhasil/', views.post_keluhan, name='keluhan')
]

event/urls.py
from django.urls import path

from . import views

app_name = 'event'

urlpatterns = [
    path('cari/', views.index, name='carievent'),
    path('tambah/', views.tambah, name='tambahevent'),
]

homepage/urls.py
from django.urls import path

from . import views

app_name = 'homepage' 

urlpatterns = [
    path('', views.tambahEmail, name='home'),
    path('notif/', views.notifEmail, name='notifEmail'),
    path('dataemail/', views.dataemail, name='dataemail'),
    path('dataemail/kirimemail/', views.kirimemail, name='kirimemail'),
    path('dataemail/tampilanemail/',views.tampilan,name='tampilanemail')     
]

study/urls.py
from django.urls import path
from .views import *

app_name = 'study'

urlpatterns = [
    path('tambah/', studyAddView, name='study'),
    path('cari/', studySearchView, name='searchstudy'),

]

tk1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('studi/', include('study.urls')),
    path('event/', include('event.urls')),
    path('support/', include('customer.urls'))
]

homepage/models.py
from django.db import models

# Create your models here.
class Email(models.Model):
    email = models.EmailField(max_length=254)

    def __str__ (self):
        return self.email

class KirimEmail(models.Model):
    subjek = models.CharField(max_length= 100)
    judul = models.CharField(max_length=120)
    deskripsi = models.TextField(max_length=255)

    def __str__ (self):
        return self.judul

    

homepage/forms.py
from django import forms
from .models import Email,KirimEmail

class emailForm(forms.ModelForm):
    class Meta:
        model = Email
        fields = ['email']

    email_attrs = {
    'type': 'text',
    'class': 'form-email',
    'placeholder':'Masukkan email'
}

    email = forms.EmailField(widget=forms.TextInput(attrs=email_attrs))
    email.widget.attrs.update({'class':'form-control'})

class kirimForm(forms.ModelForm):
    class Meta:
        model = KirimEmail
        fields = ['subjek','judul','deskripsi']

    subjek_attrs = {
    'type': 'text',
    'class': 'form-subjek',
    'placeholder':'Masukkan subjek email'
}
    judul_attrs = {
    'type': 'text',
    'class': 'form-judul',
    'placeholder':'Masukkan judul email'
}

    deskripsi_attrs = {
    'type': 'text',
    'class': 'form-deskripsi',
    'placeholder':'Masukkan deskripsi email'
}

    subjek = forms.CharField(widget=forms.TextInput(attrs=subjek_attrs))
    judul = forms.CharField(widget=forms.TextInput(attrs=judul_attrs))
    deskripsi = forms.CharField(widget=forms.Textarea(attrs=deskripsi_attrs))
    
    subjek.widget.attrs.update({'class':'form-control'})
    judul.widget.attrs.update({'class':'form-control'})
    deskripsi.widget.attrs.update({'class':'form-control'})

homepage/views.py
from django.shortcuts import render, redirect
from .forms import emailForm,kirimForm
from .models import Email,KirimEmail
from django.core.mail import send_mail, EmailMultiAlternatives
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.conf import settings
from django.contrib import messages



# Create your views here

def tambahEmail(request):
    form = emailForm(request.POST or None)
    if form.is_valid():
        form.save()
        emailnya = form.cleaned_data['email']
        form = emailForm()
        html_content = render_to_string('emailsambutan.html')
        text_content = strip_tags(html_content)
        email = EmailMultiAlternatives(
    'Terima Kasih telah mendaftarkan email !', text_content, settings.EMAIL_HOST_USER, [emailnya]
)
        email.attach_alternative(html_content,"text/html")
        email.send()
        return redirect('homepage:notifEmail')
    context = {
        'form' : form
    }
    return render(request, 'landing.html', context)

def notifEmail(request):
    return render(request, 'notif.html')

def dataemail(request):
    data = Email.objects.all()
    context = {
     'data' : data
    }
    return render(request, 'dataemail.html', context)

def kirimemail(request):
    form = kirimForm(request.POST or None)
    # data = Email.objects.values('email')
    data = Email.objects.all()
    if form.is_valid():
        form.save()
    if request.method == "POST":
        subjek  = request.POST.get('subjek')
        judul  = request.POST.get('judul')
        deskripsi = request.POST.get('deskripsi')
        html_content = render_to_string('emailcustom.html',{'subjek' :subjek,'judul':judul,'deskripsi':deskripsi})
        text_content = strip_tags(html_content)
        email = EmailMultiAlternatives(
            subjek, text_content, settings.EMAIL_HOST_USER, data
        )

        email.attach_alternative(html_content,"text/html")
        email.send()
        messages.success(request,"Email telah terkirim !")
    context = {
     'form' : form
    }
    return render(request, 'kirimemail.html', context)

def tampilan(request):
    isiemail = KirimEmail.objects.all()
    context = {
    'isiemail' : isiemail
    }
    return render(request, 'tampilanemail.html', context)

homepage/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta http-equiv="X-UA-Compatible" content="ie=edge" />
  {% block meta %} {% endblock meta %} 

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
    crossorigin="anonymous" />
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr"
    crossorigin="anonymous">
  <!-- <link rel="stylesheet" href="./Style.css" /> -->
  
  <style>
 a {
  font-size: 1.1em;
  color: #1a1a33;
}

.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f1f1f1;
  min-width: 160px;
  box-shadow: 0px 2px 15px 0px rgba(0, 0, 0, 0.2);
  z-index: 1;
}

.dropdown-content a {
  color: black;
  padding: 10px 16px;
  text-decoration: none;
  display: block;
}

.dropdown-content a:hover {
  background-color: #fddde1;
}

.dropdown:hover .dropdown-content {
  display: block;
}

.nav-item:last-child {
  padding-right: 10.5em;
}

.nav-item {
  padding: 0.9em;
}

.navbar-brand {
  padding-left: 8rem;
  font-size: 1.8em;
  color: #ed443b;
  font-weight: 700;
}

.nav-link:hover {
  color: black;
}

footer {
  background: #931f17;
  padding: 5vmin 2vmin;
  left: 0;
  display: block;
  bottom: 0;
  width: 100%;
}

footer p {
  color: #ffffff;
}


footer i {
  color: #f1f1f1;
  size: 2em;
  letter-spacing: 0.5em;
  padding-bottom: 2em;
  
}
@media only screen and (max-width: 768px) {
  .navbar-brand {
    padding-left: 1rem;
    font-size: 1.3rem;
  }
  header a{
  font-size: 0.8em;
}
}
  </style> 
  {% block style %}
  {% endblock style %}
  </head>
  <body>
      <header>
        <div class="container-fluid p-0">
        <nav class="navbar navbar-expand-lg ">
          <a class="navbar-brand" href="#">CoronaStudy</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false"
            aria-label="Toggle navigation">
            <i class="fas fa-bars"></i>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <div class="mr-auto"></div>
            <ul class="navbar-nav">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'homepage:home'%}">Home
                  <span class="sr-only">(current)</span>
                </a>
              </li>
              <li class="nav-item dropdown">
                <div class="dropdown">
                  <a href="{% url 'study:searchstudy'%}" class="nav-link">Studi Corona</a>
                  <div class="dropdown-content">
                    <a href="{% url 'study:study'%}">Tambah Studi</a>
                    <a href="{% url 'study:searchstudy'%}">Cari Studi</a>
                  </div>
                </div>
              </li>
              <li class="nav-item dropdown">
                <div class="dropdown">
                  <a href="{% url 'event:carievent'%}" class="nav-link">Event</a>
                  <div class="dropdown-content">
                    <a href="{% url 'event:tambahevent'%}">Tambah Event</a>
                    <a href="{% url 'event:carievent'%}">Cari Event</a>
                  </div>
                </div>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/support">Pesan</a>
              </li>
            </ul>
          </div>
        </nav>
      </div>
    </header>
    <main>
    
    
    {% block content %} 
    {% endblock content %} 
  </main>
  <footer>
    <div class="container-fluid p-0">
      <div class="text-center">
        <p>Kontak kami di media sosial masing-masing</p>
        <br>
        <div class="row text-center col-sm-12  justify-content-center">
          <div class="col-sm-3 text-center">
            <p>Aryo Wirapradana</p>
            <p>aryo.wirapradana@ui.ac.id</p>
            <i class="fab fa-facebook-f"></i>
            <i class="fab fa-instagram"></i>
            <i class="fab fa-twitter"></i>
            <i class="fab fa-linkedin"></i>
          </div>
          
          <div class="col-sm-3 text-center">
            <p>Ayesha Thalia</p>
            <p>ayesha.thalia@ui.ac.id</p>
            <i class="fab fa-facebook-f"></i>
            <i class="fab fa-instagram"></i>
            <i class="fab fa-twitter"></i>
            <i class="fab fa-linkedin"></i>
          </div>
          <div class="col-sm-3 text-center ">
            <p>Hasna Nadifah</p>
            <p>hasna.nadifah@ui.ac.id</p>
            <i class="fab fa-facebook-f"></i>
            <i class="fab fa-instagram"></i>
            <i class="fab fa-twitter"></i>
            <i class="fab fa-linkedin"></i>
          </div>
          <div class="col-sm-3 text-center">
            <p>Hilmy Akbar</p>
            <p>hilmy.akbar@ui.ac.id</p>
            <i class="fab fa-facebook-f"></i>
            <i class="fab fa-instagram"></i>
            <i class="fab fa-twitter"></i>
            <i class="fab fa-linkedin"></i>
          </div>
        </div>
      </div>
    </div>
  </footer>
</body>
  
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>
  
    

homepage/templates/emailcustom.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{{subjek}}</title>
        <style>
            @import url("https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,200;0,300;0,400;0,600;0,700;0,800;0,900;1,200;1,300;1,400;1,600;1,700;1,800;1,900&display=swap");
            * {
            box-sizing: border-box;
            font-family: "Nunito", sans-serif;
            }
            h2,h3{
                font-weight: 800;
color: #ed443b;
            }

        </style>
    </head>
    <body>
        <h2>{{judul}}</h2>
        <p>{{deskripsi}} </p>
        <br>
        <p>Info selengkapnya bisa kunjungi https://tk1-covidstudy.herokuapp.com/ </p>
        <h3>Keep Productive and Stay Healthy !</h3>
        <p style="font-size: 0.8em; font-style: italic;">-admin CoronaStudy</p>
    </body>
</html>

homepage/templates/landing.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta http-equiv="X-UA-Compatible" content="ie=edge" />
  <title>CoronaStudy</title>

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
    crossorigin="anonymous" />
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr"
    crossorigin="anonymous">
  <!-- <link rel="stylesheet" href="./Style.css" /> -->
  <style>
      @import url("https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,200;0,300;0,400;0,600;0,700;0,800;0,900;1,200;1,300;1,400;1,600;1,700;1,800;1,900&display=swap");
* {
  box-sizing: border-box;
  font-family: "Nunito", sans-serif;
}

header,
section {
  overflow-x: hidden;
}

header a {
  font-size: 1.1em;
  color: #1a1a33;
}

.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f1f1f1;
  min-width: 160px;
  box-shadow: 0px 2px 15px 0px rgba(0, 0, 0, 0.2);
  z-index: 1;
}

.dropdown-content a {
  color: black;
  padding: 10px 16px;
  text-decoration: none;
  display: block;
}

.dropdown-content a:hover {
  background-color: #fddde1;
}

.dropdown:hover .dropdown-content {
  display: block;
}

header .nav-item:last-child {
  padding-right: 10.5em;
}

header .nav-item {
  padding: 0.9em;
}

header .navbar-brand {
  padding-left: 8rem;
  font-size: 1.8em;
  color: #ed443b;
  font-weight: 700;
}

header .nav-link:hover {
  color: black;
}

header .row .col-md-7 {
  padding: 22vmin 1vmin;
  padding-bottom: 35vmin;
}

header .row .col-md-5 {
  padding: 4.2vmin 1vmin;
}

header .row .col-md-5 img {
  width: 100%;
}

header {
  background: #ffffff;
}

header .container .col-md-7 h6 {
  font-size: 3vmin;
  padding: 1vmin;
  color: #1a1a33;
}

header .container .col-md-7 h1 {
  color: #ed443b;
  font-size: 9.3vmin;
  font-weight: 900;
  padding: 0.1em 0em;
}

header .container .col-md-7 p {
  padding: 1vmin 5vmin;
}

header .container .col-md-7 button {
  color: #ffffff;
  width: 10em;
  height: 3em;
}

#scroll{
  font-size: 1em;
}

.primary-btn{
  border-radius: 30px;
  font-weight: bold;
  background-color: #ed443b;
  padding: 0.1em 0em;
  color: white;
  font-size: 0.8em;
}

.section-1 {
  padding: 20vmin 0vmin;
  background-color: rgb(255, 214, 214);
}

.section-1 .row .col-md-6 .pray img {
  width: 100%;
  padding: 0.4em 0;
}

.section-1 .row .col-md-6:last-child {
  position: relative;
}

.section-1 .row .col-md-6 .panel {
  
  text-align: left;
  z-index: 1;
}

.section-1 .row .col-md-6 .panel h1 {
  font-weight: 900;
  color: #ed443b;
  padding: 0.6em 0;
  font-size: 2.8em;
}

.section-1 .row .col-md-6 .panel p {
  font-size: 1.3em;
  color: rgba(0, 0, 0, 0.8);
}

.section-2 .container h1 {
  padding-top: 14vmin;
  font-weight: 900;
  color: #ed443b;
  font-size: 2.8em;
}
.section-2 .container p {
  font-size: 1.3em;
}
.section-2 .team {
  padding: 1vmin 4vmin;
}

.section-2 .team h3 {
  font-weight: 800;
  color: #ed443b;
}

.section-2 .card {
  width: 20em;
  margin-top: 6vmin;
}

.section-2 .card .card-text {
  padding: 1em;
}

.section-2 .card-body > a {
  font-size: 1.5em;
}

.section-2 .carousel-item {
  padding-left: 3rem;
}

footer {
  background: #931f17;
  overflow-x: hidden;
  padding: 5vmin 2vmin;
}

footer p {
  color: #ffffff;
}


footer i {
  color: #f1f1f1;
  size: 2em;
  letter-spacing: 0.5em;
  padding-bottom: 2em;
  
}

.section-3 {
  padding: 20vmin 0vmin;
}
.section-3 h1 {
  color: #ed443b;
  font-weight: 800;
}

@media only screen and (max-width: 768px) {
  header .navbar-brand {
    padding-left: 1rem;
    font-size: 1.3rem;
  }

  header img {
    display: none;
  }

  header{
    background-image: url('/static/img/background.jpg') ;
background-position: 70% 60%;
  }

  header .container .col-md-7 button {
    width: 5em;
    height: 1.5em;
    font-size: 1em;
  }

  header a{
    font-size: 0.8em;
  }

  .section-1 .row .col-md-6 .panel {
    position: initial;
    width: initial;
    height: initial;
    font-size: 0.8em;
    padding-left: 1rem;
    padding-right: 1rem;
  }
  .section-1 .row .col-md-6 .pray img {
  width: 60%;
  padding: 0.4em 0;
}

  .section-2 {
    font-size: small;
    /* padding-left: 1rem; */
    /* padding-right: 1rem; */
  }

  .section-3 h1 {
    font-size: 1.5rem;
  }

  .section-3 h6 {
    font-size: 1 rem;
  }
  footer .row {
    font-size: 0.7em;
    
  }
  footer i{
    padding-bottom: 3em;
  }

  #scroll{
    font-size: 0.6em;
  }
}

  </style>
</head>

<body>
  <header>
    <div class="container-fluid p-0">
      <nav class="navbar navbar-expand-lg ">
        <a class="navbar-brand" href="{% url 'homepage:home'%}">CoronaStudy</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false"
          aria-label="Toggle navigation">
          <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <div class="mr-auto"></div>
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'homepage:home'%}">Home
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item dropdown">
              <div class="dropdown">
                <a href="{% url 'study:searchstudy'%}" class="nav-link">Studi Corona</a>
                <div class="dropdown-content">
                  <a href="{% url 'study:study'%}">Tambah Studi</a>
                  <a href="{% url 'study:searchstudy'%}">Cari Event</a>
                </div>
              </div>
            </li>
            <li class="nav-item dropdown">
              <div class="dropdown">
                <a href="{% url 'event:carievent'%}" class="nav-link">Event</a>
                <div class="dropdown-content">
                  <a href="{% url 'event:tambahevent'%}">Tambah Event</a>
                  <a href="{% url 'event:carievent'%}">Cari Event</a>
                </div>
              </div>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'customer:customer'%}">Pesan</a>
            </li>
          </ul>
        </div>
      </nav>
    </div>
    <br>
    <div class="container">
      <div class="row text-center">
        <div class="col-md-7 col-sm-12">
          <h1>CoronaStudy</h1>
          <h6>Website untuk mempelajari studi tentang Covid-19 </h6>
          <br>
        </div>
        <div class="col-md-5 col-sm-10 ">
          <img src="{% static 'img/coronalanding1.svg' %}" alt="Book" />
        </div>
      </div>
    </div>
    <div class="container text-center" id= "scroll">
      <p>Scroll kebawah untuk mengetahui lebih lanjut</p>
    </div>
    <br>
  
  </header>
  <main>
    <section class="section-1">
      <div class="container text-center">
        <div class="row">
          <div class="col-md-6 ">
            <div class="pray">
              <img src="{% static 'img/coronasection1.png' %}"  alt="Pray" class="" />
            </div>
          </div>
          <div class="col-md-6 col-12">
            <div class="panel text-left">
              <h1>Apa Itu Corona ?</h1>
              <p>
                Virus Corona atau severe acute respiratory syndrome coronavirus 2 (SARS-CoV-2) adalah virus yang menyerang sistem pernapasan. Penyakit karena infeksi virus ini disebut COVID-19. Virus Corona bisa menyebabkan gangguan ringan pada sistem pernapasan, infeksi paru-paru yang berat, hingga kematian.


              </p>
            </div>
          </div>
        </div>
      </div>
    </section>
    <br>
    <br>

    <section class="section-2">
      <div class="container text-center mt-2">
        <h1>Gerakan 3M</h1>
        <p>Pemerintah lewat Satgas Covid-19 saat ini terus menggencarkan kampanye penyuluhan 3M (Memakai masker, rajin Mencuci tangan, dan selalu Menjaga jarak).
        </p>
      </div>
      <div class="container text-center mt-2">
        <div class="team row justify-content-center">
          <div class="col-md-4 col-12 text-center">
              <div class="card mr-2 d-inline-block shadow p-3 mb-5 rounded" style="width: 20rem;">
                  <div class="card-img-top">
                    <img src="{% static 'img/masker.svg' %}"  class="img-fluid border-radius p-4" alt="" style="width: 14rem;">
                  </div>
                  <div class="card-body">
                    <h3 class="card-title">Memakai Masker</h3>
                    <!-- <p class="card-text"> -->
                      Dianjurkan untuk memakai masker jika berpergian untuk menghindari virus
                      
                    </p>
                  </div>
                </div>
          </div>
          <div class="col-md-4 col-12 text-center">
            <div class="card mr-2 d-inline-block shadow p-3 mb-5 rounded" style="width: 20rem;">
                <div class="card-img-top">
                  <img src="{% static 'img/cuci.svg' %}"  class="img-fluid border-radius p-4" alt="" style="width: 14rem;">
                </div>
                <div class="card-body">
                  <h3 class="card-title">Mencuci Tangan</h3>
                  <!-- <p class="card-text"> -->
                    Dianjurkan untuk selalu mencuci tangan setiap saat, terlebih saat menyentuh atau memegang sesuatu
                    
                  </p>
                </div>
              </div>
        </div>
        <div class="col-md-4 col-12 text-center">
          <div class="card mr-2 d-inline-block shadow p-3 mb-5 rounded" style="width: 20rem;">
              <div class="card-img-top">
                <img src="{% static 'img/jarak.svg' %}"  class="img-fluid border-radius p-4" alt="" style="width: 18rem;">
              </div>
              <div class="card-body">
                <h3 class="card-title">Menjaga Jarak</h3>
                <!-- <p class="card-text"> -->
                 Menjaga jarak terhadap orang-orang agar terhindar dari paparan virus 
                  
                </p>
              </div>
            </div>
      </div>
      </div>        
      <br>
      <br>
      <br>     
    </section>
    <section class="section-3">
      <div class="container text-center">
              <h1>Daftarkan Email Anda </h1>
              <p>
                Ingin mendapatkan pemberitahuan tentang studi terbaru ? 
Daftarkan email Anda disini.
              </p>
                <div class="form-group text-center">
                  <form action = "" method="POST" >
                    {% csrf_token %} {{form.as_p}}
<button type="Submit" class="btn btn-light px-4 py-2 primary-btn">Save</button>
                  </form>
                </div>
      </div>
    </section>
    <br>
    <br>
    </main>

  <footer>
    <div class="container-fluid ">
      <div class="text-center">
        <p>Kontak kami di media sosial masing-masing</p>
        <br>
        <div class="row text-center col-sm-12  justify-content-center">
          <div class="col-sm-3 text-center">
            <p>Aryo Wirapradana</p>
            <p>aryo.wirapradana@ui.ac.id</p>
            <i class="fab fa-facebook-f"></i>
            <i class="fab fa-instagram"></i>
            <i class="fab fa-twitter"></i>
            <i class="fab fa-linkedin"></i>
          </div>
          
          <div class="col-sm-3 text-center">
            <p>Ayesha Thalia</p>
            <p>ayesha.thalia@ui.ac.id</p>
            <i class="fab fa-facebook-f"></i>
<i class="fab fa-instagram"></i>
<i class="fab fa-twitter"></i>
<i class="fab fa-linkedin"></i>
          </div>
          <div class="col-sm-3 text-center ">
            <p>Hasna Nadifah</p>
            <p>hasna.nadifah@ui.ac.id</p>
            <i class="fab fa-facebook-f"></i>
<i class="fab fa-instagram"></i>
<i class="fab fa-twitter"></i>
<i class="fab fa-linkedin"></i>
          </div>
          <div class="col-sm-3 text-center">
            <p>Hilmy Akbar</p>
            <p>hilmy.akbar@ui.ac.id</p>
            <i class="fab fa-facebook-f"></i>
<i class="fab fa-instagram"></i>
<i class="fab fa-twitter"></i>
<i class="fab fa-linkedin"></i>
          </div>

        </div>

      </div>
    </div>
  </footer>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>
  <!-- <script src="./main.js"></script> -->
</body>

</html>